syntax = "proto3";

package api;

import "google/api/annotations.proto";

option go_package = "github.com/alexschoenwitz/mask-invaders/api";

service Server {
  rpc CreateGame(CreateGameRequest) returns (CreateGameResponse) {
    option (google.api.http) = {
      post: "/v1/games"
      body: "*"
    };
  }

  rpc ListGames(ListGamesRequest) returns (ListGamesResponse) {
    option (google.api.http) = {get: "/v1/games"};
  }

  rpc StartGame(StartGameRequest) returns (StartGameResponse) {
    option (google.api.http) = {
      post: "/v1/games/{game_id}/start"
      body: "*"
    };
  }

  rpc GetState(GetStateRequest) returns (GetStateResponse) {
    option (google.api.http) = {get: "/v1/games/{game_id}/state"};
  }

  rpc GetStateHistory(GetStateHistoryRequest) returns (GetStateHistoryResponse) {
    option (google.api.http) = {get: "/v1/games/{game_id}/state:history"};
  }

  rpc PostAction(PostActionRequest) returns (PostActionResponse) {
    option (google.api.http) = {
      post: "/v1/games/{game_id}/action"
      body: "*"
    };
  }

  rpc Register(RegisterRequest) returns (RegisterResponse) {
    option (google.api.http) = {
      post: "/v1/games/{game_id}/register"
      body: "*"
    };
  }
}

message CreateGameRequest {}

message CreateGameResponse {
  string game_id = 1;
}

message ListGamesRequest {}

message ListGamesResponse {
  repeated string game_ids = 1;
}

message StartGameRequest {
  string game_id = 1;
}

message StartGameResponse {}

message ResetGameRequest {
  string game_id = 1;
}

message ResetGameResponse {}

message GetStateRequest {
  string game_id = 1;
}

message GetStateResponse {
  State state = 1;
}

message GetStateHistoryRequest {
  string game_id = 1;
}

message GetStateHistoryResponse {
  repeated State states = 1;
}

message State {
  map<string, City> cities = 1;
  repeated Movement movements = 2;
  map<string, Distance> distances = 3;
  int64 turn = 4;
  map<string, Mine> mines = 5;
}

message Mine {
  string id = 1;
  map<string, Resource> resources = 2;
  bool claimed = 3;
}

message Resource {
  int64 amount = 1;
}

message City {
  string id = 1;
  string player = 2;
  map<string, int64> troops = 3;
  map<string, Resource> resources = 4;
}

message Movement {
  string from = 1;
  oneof to {
    string city = 2;
    string mine = 6;
  }
  map<string, int64> troops = 3;
  int64 arriving_turn = 4;
  string player = 5;
}

message Distance {
  string edge = 1;
  int64 distance = 2;
}

message PostActionRequest {
  string game_id = 1;
  Action action = 2;
}

message PostActionResponse {}

message Action {
  string player = 1;
  oneof action {
    Attack attack = 3;
    None none = 4;
    CreateTroop create_troop = 5;
  }
}

message Attack {
  string from = 1;
  oneof to {
    string city = 2;
    string mine = 4;
  }
  map<string, int64> troops = 3;
}

message None {}

message CreateTroop {
  string in = 1;
  string type = 2;
}

message RegisterRequest {
  string game_id = 1;
  string name = 2;
}

message RegisterResponse {
  string id = 1;
  string token = 2;
}
