syntax = "proto3";

package api;

import "google/api/annotations.proto";

option go_package = "github.com/alexschoenwitz/mask-invaders/api";

service Server {
  rpc StartGame(StartGameRequest) returns (StartGameResponse) {
    option (google.api.http) = {
      post: "/v1/start"
      body: "*"
    };
  }
  rpc ResetGame(ResetGameRequest) returns (ResetGameResponse) {
    option (google.api.http) = {
      post: "/v1/reset"
      body: "*"
    };
  }
  rpc GetState(GetStateRequest) returns (GetStateResponse) {
    option (google.api.http) = {get: "/v1/state"};
  }
  rpc GetStateHistory(GetStateHistoryRequest) returns (GetStateHistoryResponse) {
    option (google.api.http) = {get: "/v1/state:history"};
  }
  rpc PostAction(PostActionRequest) returns (PostActionResponse) {
    option (google.api.http) = {
      post: "/v1/action"
      body: "*"
    };
  }
  rpc Register(RegisterRequest) returns (RegisterResponse) {
    option (google.api.http) = {
      post: "/v1/register"
      body: "*"
    };
  }
}

message StartGameRequest {}

message StartGameResponse {}

message ResetGameRequest {}

message ResetGameResponse {}

message GetStateRequest {}

message GetStateResponse {
  State state = 1;
}

message GetStateHistoryRequest {}

message GetStateHistoryResponse {
  repeated State states = 1;
}

message State {
  map<string, City> cities = 1;
  repeated Movement movements = 2;
  map<string, Distance> distances = 3;
  int64 turn = 4;
  map<string, Mine> mines = 5;
}

message Mine {
  map<string, Resource> resources = 1;
}

message Resource {
  int64 amount = 1;
}

message City {
  string player = 1;
  map<string, int64> troops = 2;
  map<string, Resource> resources = 3;
}

message Movement {
  string from = 1;
  string to = 2;
  map<string, int64> troops = 3;
  int64 arriving_turn = 4;
  string player = 5;
}

message Distance {
  string edge = 1;
  int64 distance = 2;
}

message PostActionRequest {
  Action action = 1;
}

message PostActionResponse {}

message Action {
  string player = 1;
  oneof action {
    Attack attack = 3;
    None none = 4;
    CreateTroop create_troop = 5;
  }
}

message Attack {
  string from = 1;
  string to = 2;
  map<string, int64> troops = 3;
}

message None {}

message CreateTroop {
  string in = 1;
  string type = 2;
}

message RegisterRequest {
  string name = 1;
}

message RegisterResponse {
  string id = 1;
  string token = 2;
}
